% %
% figure (11)
% subplot(311)
% plot(t0,x_p_N-xpm_Nh')
% ylabel('X err position in meter')
% subplot(312)
% plot(t0,y_p_N-ypm_Nh')
% ylabel('Y err position in meter')
% xlabel('Time in seconds')
% subplot(313)
% plot(t0,z_p_N-zpm_Nh')
% ylabel('Z err position in meter')
% xlabel('Time in seconds')
% grid
% %
% figure (12)
% plot3(x_p_N,y_p_N,z_p_N,'r',xpm_Nh,ypm_Nh,zpm_Nh,'b',xr1,yr1,zr1,'r*',xr2,yr2,zr2,'r*',xr3,yr3,zr3,'r*',xr4,yr4,zr4,'r*')
% xlabel('X position in m')
% ylabel('Y position in m')
% axis([-50 50 -50 50 -50 50])
% grid
% %
% figure (13)
% subplot(311)
% plot(t0,xam_Nh/g)
% ylabel('X accel g')
% subplot(312)
% plot(t0,yam_Nh/g)
% ylabel('Y accel in g')
% xlabel('Time in seconds')
% subplot(313)
% plot(t0,(zam_Nh+g)/g)
% ylabel('Z accel in g')
% xlabel('Time in seconds')
% grid
% %
% figure (14)
% subplot(311)
% plot(t00,x_p_N,'r',t00,xpm_Nh,'b--')
% xlabel('Time in sec')
% ylabel('X position in m')
% subplot(312)
% plot(t00,y_p_N,'r',t00,ypm_Nh,'b--')
% xlabel('Time in sec')
% ylabel('Y position in m')
% subplot(313)
% plot(t00,z_p_N,'r',t00,zpm_Nh,'b--')
% xlabel('Time in sec')
% ylabel('Z position in m')
%
figure (15)
subplot(311)
plot(t00,(bgx0-bgx_h)*r2d,'r')
%xlabel('Time in sec')
ylabel('X gyro bias err in deg/sec')
subplot(312)
plot(t00,(bgy0-bgy_h)*r2d,'b')
%xlabel('Time in sec')
subplot(313)
plot(t00,(bgz0-bgz_h)*r2d,'g')
%xlabel('Time in sec')
ylabel('Z gyro bias err in deg/sec')
%
 figure (5)
 subplot(311)
 plot(t0(n1:n2),x_err(n1:n2))
 ylabel('X err position in meter')
 subplot(312)
 plot(t0(n1:n2),y_err(n1:n2))
 ylabel('Y err position in meter')
% xlabel('Time in seconds')
 subplot(313)
 plot(t0(n1:n2),z_err(n1:n2))
 ylabel('Z err position in meter')
 xlabel('Time in seconds')
% grid